services:
  db:
    container_name: db.aqe.local
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust # IMPORTANT allows all connections without a password - experimental only!
    ports:
      - "${APP_DATABASE_PORT:-8432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: another_quote_editor_net
    enable_ipv6: true
    driver: bridge
