# See: https://mise.jdx.dev/environments/#env-directives

activate_aggressive = true

[env]
_.file = '.env.development'

[status]
missing_tools = "if_other_versions_installed"
show_env = true
show_tools = true
